### PR TITLE
Added Bengali(BN) language support

### LINKED ISSUE #6: Add support for BN lang
In reference to [this](https://github.com/octave-online/octave-online-server/issues/27#issuecomment-723175872), I want to add Bengali(BN) language to Octave.

### PR DESCRIPTION
**Pull request by Neilblaze**
This PR includes Bengali translation for Octave-Online.

Fixes #6

### CODE REVIEW

**Comment by Neilblaze** [comment]
@sffc have a look! Let me know if I need to change something! :smile:

**Review by sffc — APPROVED** [review]
This looks fantastic!  Thank you for the contribution!

**Comment by Neilblaze** [comment]
@sffc This PR has been merged, but on the Octave-Online site, the `Bengali` option in the set language dropdown isn't available yet. Any idea why this is happening?

**Comment by sffc** [comment]
image

**Pull request merged**
